name: Get Hashes

on:
  push:
    branches:
      - main
jobs:
  get-hashes:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Build and analyze
        run: sh get_hashes.sh